/* eslint-disable @next/next/no-html-link-for-pages */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
export default function Classes() {
  return (
    //List

    <div className={styles.container}>
      <Head>
        <title>Classes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Classes:
        </h1>
    <h2> Gen Ed</h2>
        <ul>
    <h4>General Ed Group A: English and Communication Group </h4>
   <li> English 100: General English Composition </li>
    <li> English 101: College Reading </li>
    <li> Communication 101: Oral Presentation Skills </li> 
    </ul>
       <ul>
       <h4>General Ed Group B: Math </h4>
    <li> Math 100: College Algebra </li>
    <li> Math 103: College Stats </li>
    <li> Math 104: Buisness and Consumer Math </li>
    <li> Math 130: STEM Prep Part 1: Trigonometry </li>
    <li> Math 135:  STEM Prep Part 2: College Precalculus </li>
    </ul>
    <ul>
    <h4>General Ed Group C: Enlightenment and Life Skills </h4>
    <li> Math 100: College Algebra </li>
    <li> Math 103: College Stats </li>
    <li> Math 104: Buisness and Consumer Math </li>
    <li> Math 130: STEM Prep Part 1: Trigonometry </li>
    <li> Math 135:  STEM Prep Part 2: College Precalculus </li>
    </ul>
      </main>
    </div>
  )
}