/* eslint-disable @next/next/no-html-link-for-pages */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
export default function Classes() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Classes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Classes:
        </h1>
    <h2> Gen Ed</h2>
        <ul>
    General Ed Group A: English and Communication Group
   <li> English 100: General English Composition </li>
    <li> English 101: College Reading </li>
    <li> Communication 101: Oral Presentation Skills </li> 
    </ul>



      </main>
    </div>
  )
}