/* eslint-disable @next/next/no-html-link-for-pages */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link';
export default function Classes() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Classes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.classpage}>
        <h1 className={styles.title}>
          Classes:
        </h1>
    <h2> Gen Ed</h2>
        <ul>
    <h4>General Ed Group A: English and Communication Group </h4>
   <li> English 100: General English Composition (4 units)</li>
    <li> English 101: College Reading  (4 units)</li>
    <li> Communication 101: Oral Presentation Skills (3 units) </li> 
    </ul>
       <ul>
       <h4>General Ed Group B: Math </h4>
    <li> Math 100: College Algebra (4 units) </li>
    <li> Math 103: College Stats (4 units) </li>
    <li> Math 104: Buisness and Consumer Math (3 units) </li>
    <li> Math 130: STEM Prep Part 1: Trigonometry (4 units) </li>
    <li> Math 135:  STEM Prep Part 2: College Precalculus (4 units) </li>
    </ul>
    <ul>
    <h4>General Ed Group C: Enlightenment </h4>
    <li> Philosophy 100: Introduction to Philosophy (3 units)</li>
    <li> Zen 100: Introduction to Zen Studies (3 units) </li>
    <li> Zen 103: Enlightement Techniques I (3 units) </li>
    <li> Zen 105: Enlightement Techniques II (3 units) </li>
    </ul>
    <ul>
    <h4>General Ed Group D: Electives </h4>
    <li> Zen 108:  Yoga and Meditation (2 units) </li>
    <li> Art 100: Introduction to Art (3 units)</li>
    <li> Art 101: Art History (3 units) </li>
    <li> Music 113: Survey of Music  (3 units)</li>
    <li> Music 114: History of Rock & Roll (3 units) </li>
    <li> Film 101: History of Film (3 units) </li>
    </ul>
    <ul>
    <h4>General Ed Group E: History </h4>
    <h5> Group A:</h5>
    <li> History 100: Pre World History (3 units) </li>
    <li> History 101: Modern World History (3 units) </li>
    <h5> Group B:</h5>
    <li> History 110: Ancient US History (3 units) </li>
    <li> History 111: Modern US History (3 units) </li>
    <h5> Group C:</h5>
    <li> Political Science 100: Introduction to Political Science (3 units) </li>
    </ul>
    <ul>
    <h4>General Ed Group F: Science </h4>
    <li> Bio 100: General Biology (with lab) (4 units) </li>
    <li> Chemistry 100: General Chemistry (with lab) (4 units)</li>
    <li> Zoology 100: General Zoology (with lab) (4 units)</li>
    </ul>
    <Link legacyBehavior href="/"> 
        <a className="btn btn-success">Home</a>
        </Link>
      </main>
    </div>
  )
}