import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to The Zen Inspiration School
        </h1>
        <div className={styles.grid}>
        <Link href="/About">
          <a className="btn btn-success">About Me</a>
        </Link>
        <h4> Nature and Enlightenment: </h4>
        <Link href="/MenuNature">
          <a className="btn btn-success">Menu for the Nature site</a>
        </Link>
        <h4> Quotes: </h4>
        <Link href="/Quotes">
          <a className="btn btn-success">Quotes</a>
        </Link>
        <h4>Contact Me: </h4>
        <Link href="/Contact">
          <a className="btn btn-success">Contact Me</a>
        </Link>
        </div>
      </main>
    </div>
  )
}
