import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to The Zen Inspiration School
        </h1>








        <div className={styles.grid}>
        <Link href="/About">
          <a className="btn btn-success">About Me</a>
        </Link>
        <h4> Nature and Enlightenment: </h4>
        <Image  alt="A small purple flower ."src="/flower.jpg" width="200" height="200"/>
        <br/>
        <Image  alt="An animated blue cat."src="/cartooncat.png" width="200" height="200"/>
        <br/>
        <Link href="/MenuNature">
          <a className="btn btn-success">Menu for the Nature site</a>
        </Link>
        <h4> Quotes: </h4>
        <Image alt="asdf" src="/quotes.png" width="200" height="200"/>
        <br/>
        <Link href="/Quotes">
          <a className="btn btn-success">Quotes</a>
        </Link>
        <h4>Contact Me: </h4>
        <Image  alt="A yellow sticky note saying Call Me."src="/contact.png" width="200" height="200"/> 
        <br/>
        <Link href="/Contact">
          <a className="btn btn-success">Contact Me</a>
        </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
