import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to The Zen Inspiration School
        </h1>
        <div className={styles.grid}>
        <Link href="/About" className="btn btn-success">
          About Me
        </Link>
        <h4> Nature and Enlightenment: </h4>
        <Link href="/MenuNature" className="btn btn-success">
          Menu for the Nature site
        </Link>
        <h4> Quotes: </h4>
        <Link href="/Quotes" className="btn btn-success">
          Quotes
        </Link>
        <h4>Contact Me: </h4>
        <Link href="/Contact" className="btn btn-success">
          Contact Me
        </Link>
        </div>
      </main>
    </div>
  );
}
